// Procedural feature flex (Tier 2): three motion beats whose markup is generated by render(env) JS —
// a data-driven chart, a computed-geometry spiral, and a generative travelling wave. Loaded + linted by
// resolveMotionGraphic (the real build path), composited by the live KinoVideo composition.
// Run: `npx tsx examples/motion-flex/render-proc-flex.ts`  (set FLEX_VIDEO=1 to render the mp4).
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { mkdtempSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { renderStills, renderVideo } from "../../src/render/render.js";
import { resolveMotionGraphic } from "../../src/render/motiongraphic.js";
import type { KinoProps } from "../../src/render/props.js";

const here = dirname(fileURLToPath(import.meta.url));
const project = { assetPath: (rel: string) => join(here, rel) };
const GOLD = "#d99a20";
const theme = {
  font: '"Helvetica Neue", Helvetica, Arial, sans-serif',
  night: "#0b1020", mint: "#80e2b4", green: "#0c8d64", gold: GOLD, white: "#ffffff",
  captionFontSize: 74, captionStroke: 9,
};

const props: KinoProps = {
  theme, fps: 30, avatar: null, avatarWindows: [], voTrack: null, logo: null,
  background: {
    kind: "aurora", image: null, customCode: null,
    params: { colorA: theme.mint, colorB: theme.green, colorC: GOLD, intensity: 0.55 },
    keyframes: [], triggers: [],
  },
  disclosure: "procedural motion graphics demo — render(env) in JS",
  // Beats overlap ~0.3s; each graphic exit-fades itself via (1 - var(--progress)).
  segments: [
    {
      kind: "motion", caption: "", startSec: 0, endSec: 5.0,
      motion: resolveMotionGraphic(
        { source: "proc/chart.js", triggers: [{ at: 0.2, action: "pulse" }, { at: 2.6, action: "pulse" }] },
        project,
      ),
    },
    {
      kind: "motion", caption: "", startSec: 4.7, endSec: 9.7,
      motion: resolveMotionGraphic(
        { source: "proc/field.js", triggers: [{ at: 0.3, action: "pulse" }, { at: 2.6, action: "pulse" }] },
        project,
      ),
    },
    {
      kind: "motion", caption: "", startSec: 9.4, endSec: 14.4,
      motion: resolveMotionGraphic(
        { source: "proc/wave.js", triggers: [{ at: 0.4, action: "pulse" }, { at: 2.6, action: "pulse" }] },
        project,
      ),
    },
  ],
};

const outDir = join(here, "out");
mkdirSync(outDir, { recursive: true });

if (process.env.FLEX_VIDEO) {
  const outs = await renderVideo({ props, publicDir: mkdtempSync(join(tmpdir(), "pflex-")), formats: ["9:16"], outDir, title: "motion-proc-flex" });
  console.log("video:", outs.join(", "));
} else {
  const frames = [
    { frame: 75, name: "p01-chart" },   // chart mid-grow (progress ~0.5)
    { frame: 135, name: "p01b-chart" }, // chart settled
    { frame: 250, name: "p02-field" },  // spiral (later, fuller reveal)
    { frame: 360, name: "p03-wave" },   // wave + wordmark
  ];
  const outs = await renderStills({ props, publicDir: mkdtempSync(join(tmpdir(), "pflex-")), format: "9:16", frames, outDir });
  console.log("stills:\n" + outs.join("\n"));
}
