// Discovery: print the CSS-variable contract + rules an agent codes a motion-graphic HTML file
// against. Mirrors `kino backgrounds`/`kino elements`. The graphic is referenced from the spec
// (kind:"motion" or motionOverlay) and driven entirely by these kino-set variables.
import { listMotionIds } from "../media/motionLib.js";

export function motionHelpText(): string {
  const lib = listMotionIds();
  const libLine = lib.length
    ? `Bundled library ids (bare source, no path): ${lib.join(", ")}`
    : "Bundled library: (empty assets-lib/motion/)";
  return [
    "Motion graphics — author a self-contained HTML/CSS/.js file in assets/motion/, OR use a bare",
    "id from assets-lib/motion/ (e.g. \"source\": \"prompt-type\"). Reference from the spec:",
    '  { "kind": "motion", "source": "motion/x.html" | "prompt-type", "text": "..." }',
    "  or \"motionOverlay\". JSON owns timing; CSS/JS reads kino-set variables.",
    '  `text` is the SPOKEN line and is optional — for a purely visual beat omit it and give "dur"',
    "  instead. The beat then speaks nothing and draws no caption. Note an unspoken",
    "  beat has no word timings, so atWord / --kino-words-shown / env.words do not fire on it; drive it",
    "  off --progress. A beat with neither text nor dur is rejected (nothing defines its length).",
    "  `dur` is NOT the rendered length: beats are separated by a fixed 0.32s gap, and a beat's",
    "  visuals hold until the next beat starts, so every beat but the last renders for dur + 0.32 and",
    "  --progress spans that. \"dur\": 3.4 renders 3.72s. Take beat lengths from `kino inspect`",
    "  (durSec / interBeatGapSec) — a keyframe `at` you sized against dur lands early.",
    "",
    `  ${libLine}`,
    "",
    "  --frame      integer frame within the beat",
    "  --t          seconds within the beat — real render clock; use for scrubbers / elapsed timers",
    "  --progress   0 → 1 across the beat (entrances, camera — not playback clocks)",
    "  --kino-in / --kino-out / --kino-inout / --kino-overshoot / --kino-spring / --kino-edge",
    "               eased progress curves (prefer for entrances/camera/seam-safe life)",
    "  Keyframe ease (per keyframe `ease` on params): linear · easeIn · easeOut · easeInOut ·",
    "    easeInQuad/easeOutQuad/easeInOutQuad · easeInCubic/easeOutCubic/easeInOutCubic ·",
    "    easeInQuart/easeOutQuart/easeInOutQuart · easeInExpo/easeOutExpo/easeInOutExpo ·",
    "    overshoot · spring",
    "  --pulse      0 → 1 envelope fired by spec triggers ({ at, action:'pulse' })",
    "  --cam-vel    |cam[t] − cam[t−1]| × fps (0 when no cam param or frame 0)",
    "  --cam-blur   camBlur × camVel × (1 − cam), px-ready, clamped 0..24 (default camBlur=12)",
    "  --kino-vel / --kino-vel-x / --kino-vel-y / --kino-vel-dx / --kino-vel-dy / --kino-vel-angle",
    "               how far THIS element moved this frame (composition px per frame) — opt in per",
    "               element with data-kino-vel; 0 everywhere else. See \"Per-element velocity\" below.",
    "  --<param>    every key in the spec's params, tweened by keyframes (e.g. --pct, --cam)",
    "  --kino-green --kino-night --kino-white --kino-mint --kino-gold   brand palette",
    "  --kino-font  brand font family",
    "  --kino-caption-bottom   px from the frame bottom where kino's caption sits (0 = no caption",
    "               this beat). Keep your own text clear of it — sit above the band with",
    "               bottom:calc(var(--kino-caption-bottom) + 24px), or below it toward the frame",
    "               bottom with bottom:max(24px, calc(var(--kino-caption-bottom) - 160px)).",
    "  --kino-words-shown / --kino-word-count   VO-locked typed UI. words-shown is CONTINUOUS —",
    "               each word contributes its elapsed fraction across its spoken span, so gated",
    "               reveals (clamp(0, calc(var(--kino-words-shown) - i), 1)) ease, not step.",
    "               Tier-2 JS also gets env.words = beat-relative { word, start, end }[] — same",
    "               TTS timings as the caption engine.",
    "               Recipes: skills/speech-synced-ui (burst typewriter, camera-follows-typing).",
    "",
    "Example (a bar that grows to --pct and a title that rises in):",
    "  <style>",
    "    .bar   { position:absolute; left:8%; bottom:30%; height:48px;",
    "             width:calc(var(--pct) * 1%); background:var(--kino-mint); border-radius:8px; }",
    "    .title { position:absolute; left:8%; bottom:38%; font-family:var(--kino-font);",
    "             color:var(--kino-white); font-weight:900; font-size:64px;",
    "             opacity:var(--progress);",
    "             transform:translateY(calc((1 - var(--progress)) * 40px)); }",
    "  </style>",
    "  <div class='title'>86% match</div><div class='bar'></div>",
    "",
    "Drive it from the spec:",
    '  "params": { "pct": 0 }, "keyframes": [{ "at": 0, "params": { "pct": 0 } }, { "at": 0.6, "params": { "pct": 86 }, "ease": "overshoot" }]',
    "  · `at` is beat-relative SECONDS (0 = beat start), like zoomKeyframes / triggers — NOT a 0-1 fraction.",
    "  · ONE keyframe holds that value static for the whole beat; give a START + END pair to animate (a lone",
    "    { at:0.2, pct:86 } paints 86 from frame 0 — the bar never grows).",
    "",
    "Stagger (reveal items one after another — don't let everything land at once):",
    "  · Easiest — auto-stagger a whole list with sibling-index() (one rule, no extra params):",
    "      .item { --d: calc((sibling-index() - 1) * .08);",
    "              opacity: clamp(0, calc((var(--progress) - .2 - var(--d)) * 8), 1); }",
    "  · Or give each element its own slice of --progress:",
    "      .a { opacity: clamp(0, calc(var(--progress) * 10), 1); }",
    "      .b { opacity: clamp(0, calc((var(--progress) - .12) * 10), 1); }",
    "  · Or expose a param per element (--w1/--w2 …) and offset the keyframe `at` times to get",
    "    spring / overshoot / easeInOut easing per element.",
    "",
    "Keep it calm: easeInOut (or a smoothstep ramp) reads smoother than spring; let entrances last",
    "~1s and add slow continuous life off --t (e.g. transform:rotate(calc(var(--t) * 20deg))).",
    "",
    "Use real @keyframes (kino scrubs them across the beat — add class=\"kino-anim\"):",
    "  <style>@keyframes pop{0%{transform:scale(.6);opacity:0} 60%{transform:scale(1.06)}",
    "                        100%{transform:scale(1);opacity:1}}",
    "         .badge{animation-name:pop}</style>",
    "  <div class='badge kino-anim'>NEW</div>",
    "  · The class goes on the element that HAS the animation, never on a wrapper. On a parent it",
    "    does nothing: the child keeps CSS's default animation-duration of 0s and paints its END",
    "    state from frame 0, so the beat looks already-finished rather than broken. (Linted.)",
    "  · The animation plays 0→100% across the WHOLE beat — a % stop is a fraction of the beat, not",
    "    of an entrance. A snappy 0.5s entrance on a 4s beat must finish by ~12% and then hold:",
    "      @keyframes fall{0%{...} 12%{...} 100%{/* same as 12% — hold */}}",
    "    Writing the entrance across 0→100% makes one element take the entire beat to arrive.",
    "  · Stagger items with --kino-delay, in PROGRESS units (0..1 = the beat), NOT seconds:",
    "      .kw{ --kino-delay: calc((sibling-index() - 1) * .1); }   /* .1 = a tenth of the beat */",
    "    Keyframe X% then fires at progress = delay + X/100.",
    "  · Don't set animation-play-state — kino manages pausing. (CSS transition is still not allowed.)",
    "",
    "Gradient-filled text — background-clip:text + tight (negative) letter-spacing clips the last",
    'glyph\'s right edge (the gradient only paints the content box). Add class="kino-cliptext":',
    "  .big{ background-image:linear-gradient(var(--kino-mint), var(--kino-white));",
    "        -webkit-background-clip:text; background-clip:text; color:transparent; letter-spacing:-.04em }",
    "  <div class='big kino-cliptext'>98%</div>",
    "",
    "Built-in helper classes (opt-in; no @keyframes to write; all frame-driven + determinism-safe):",
    "  · Reveals that complete in the first ~third of the beat then hold — class=\"kino-rise\" (fade +",
    "    slide up), \"kino-blur-rise\", \"kino-pop\" (overshoot), \"kino-wipe\" (clip-reveal). Stagger a",
    "    list with --kino-delay: e.g. .item{ --kino-delay: calc((sibling-index() - 1) * .08) }.",
    "  · class=\"kino-pulse\" — opacity+scale pop on each spec trigger { at, action:'pulse' } (place the",
    "    triggers at VO word times from `kino inspect` to punch on the words). Accent-only: sets",
    "    opacity:var(--pulse,0) so the element is hidden between triggers — never on always-visible",
    "    primary chrome (play buttons, nav bars). Use var(--pulse) in your own CSS for subtle reacts.",
    "  · class=\"kino-camera\" — velocity-blur on camera moves. Keyframe cam:0→1 in spec params;",
    "    blur peaks mid-move and clears on settle. Optional camBlur param (default 12). Tier-2:",
    "    env.camVel / env.camBlur.",
    "  · class=\"kino-smear\" — motion blur from the element's OWN travel. Implies data-kino-vel, so",
    "    the class is the whole opt-in. Reach for it whenever something moves fast INSIDE the page: the",
    "    automatic layer blur reads the segment's camera track, so a CSS transform here is invisible to",
    "    it and renders perfectly sharp with no warning. Tune with --kino-smear (px of blur per",
    "    px/frame, default .05) and --kino-smear-max (px ceiling, default 18).",
    "  · class=\"kino-fade-edges\" — feathers the top/bottom edges (scrolling lists / overflowing text).",
    "  · Easing tokens for your own @keyframes: animation-timing-function:var(--kino-ease-out) (also",
    "    --kino-ease-in-out, --kino-ease-overshoot, --kino-ease-spring).",
    "  · Texture & finish: class=\"kino-grain\" (film grain), \"kino-vignette\" (edge darken), \"kino-mesh\"",
    "    (soft palette-gradient background), \"kino-shadow\" (soft drop-shadow). Or apply the injected SVG",
    "    filters directly: filter:url(#kino-grain) or filter:url(#kino-displace) (organic edge wobble).",
    "  · Directional smear + channel split (CSS blur() is isotropic, so these are not expressible in",
    "    plain CSS): filter:url(#kino-smear-x) / #kino-smear-x-lg — horizontal drag; #kino-smear-y /",
    "    #kino-smear-y-lg — vertical. filter:url(#kino-rgb) — true per-channel RGB split (red left,",
    "    blue right), not a tinted text-shadow copy. Strengths are fixed (SVG filter attributes can't",
    "    read CSS vars) — cross-fade the two rungs, or emit your own <filter> from a Tier-2 page for a",
    "    scrubbable stdDeviation. Pair a smear with fast travel for a motion-blur read.",
    "  · font-weight is a no-op by default: only the caption cut of the brand font is staged, so one face",
    "    answers every weight. Opt in with spec or brand `fontWeights: [400, 500, 800]` to stage real cuts",
    "    (spec overrides brand; each is inlined into every raster, so ask for what you use).",
    "  · Camera-driven blur, already computed for you: var(--cam-blur) is px-ready and rises only while",
    "    the camera moves — filter:blur(calc(var(--cam-blur) * 1px)).",
    "",
    "Per-element velocity — data-kino-vel (a real per-glyph/per-card motion smear):",
    "  --cam-blur and the automatic layer blur describe a whole SURFACE moving; neither can smear eight",
    "  letters independently inside one page, and CSS cannot read an element's own displacement. Mark the",
    "  element and kino measures its travel for you:",
    "    <span class='letter' data-kino-vel>S</span>",
    "    .letter{ filter:blur(calc(var(--kino-vel-x) * .4px)) }   /* drags only while it moves */",
    "  · Sampled as a CENTRAL difference across the frames either side, so an easing that decelerates",
    "    into a keyframe does not blink the effect off for one frame mid-move. True rest still reads 0.",
    "  · Units are composition px PER FRAME (the distance covered while the shutter is open), measured on",
    "    the element's post-transform box — so translate/scale/rotate and scrubbed @keyframes all count.",
    "  · --kino-vel = speed · --kino-vel-x/-y = unsigned per-axis speed (safe inside blur(), where a",
    "    negative length would invalidate the whole declaration) · --kino-vel-dx/-dy = SIGNED direction",
    "    (for translate/skew trails) · --kino-vel-angle = deg, e.g. rotate(var(--kino-vel-angle)) on a",
    "    wrapper whose child carries #kino-smear-x, to point a fixed smear along the path.",
    "  · All six are 0 on an element that didn't opt in, and 0 while it is parked — so the effect appears",
    "    only during the move, and a still page pays for nothing (measuring costs a layout pass, so only",
    "    marked elements are measured).",
    "  · Tier-2 (.js) authors compute their own geometry and don't need this; it exists for Tier-1 CSS.",
    "",
    "Path morphing — data-kino-morph-from / -to (one shape BECOMING another):",
    "  `d` is only animatable via SMIL or transition, both banned here, so the usual stand-in is an",
    "  opacity crossfade between two shapes — which reads as two shapes, never as one becoming the other.",
    "  Give both endpoints and kino interpolates `d` every frame:",
    "    <svg viewBox='0 0 100 100'><path fill='var(--kino-mint)'",
    "         data-kino-morph-from='M20,74 C34,24 66,24 80,74 Z'",
    "         data-kino-morph-to='M46,74 C46,26 54,26 54,74 Z'",
    "         data-kino-morph-t='var(--morph)'/></svg>",
    "  · The two paths must have the SAME command structure — same letters, same order, same case (L vs l",
    "    is absolute vs relative), and equal arc flags. Pad the simpler shape with extra (even degenerate)",
    "    segments to match: above, a dome and a bar are both M + one C + Z. A mismatch is REJECTED at",
    "    validate, naming the offending command, rather than cutting between the shapes at t=0.5.",
    "  · data-kino-morph-t is optional (default var(--progress)) and is a unitless 0→1 evaluated by kino,",
    "    not by CSS: a number, var(--x[, fallback]), or arithmetic in calc/clamp/min/max. Stagger a row by",
    "    giving each path its own offset — data-kino-morph-t='clamp(0, calc((var(--progress) - .15) * 3), 1)'.",
    "    Values outside 0..1 are clamped, so --kino-overshoot/--kino-spring are safe drivers. CSS-only",
    "    functions (sibling-index(), attr(), env()) are NOT available in this attribute.",
    "  · A shape that changes profile more than once needs a SEQUENCE, not two endpoints:",
    "      data-kino-morph-stops='0: M… | 0.55: M… | 1: M…'   (| between stops, : after each position)",
    "    Positions are 0..1 on the driver, may be listed in any order, and the shape holds at each end",
    "    rather than extrapolating. Every consecutive pair must match structurally, checked at validate.",
    "    This is also the only way to morph inside a <mask>: cross-fading two paths there drops mask",
    "    luminance to ~0.5 during the handoff, so whatever the mask protects renders half-visible.",
    "  · Morphing LETTERFORMS needs the glyph as geometry, which text-as-text cannot give you. Run",
    "    `kino glyphs \"Showreel\" --font Inter --size 120` for real outlines as <path d>, then morph,",
    "    stroke-dash or clip them like any path. Two runs of the same string always share command",
    "    structure, so they are a valid stops pair. (For text you are NOT morphing, prefer <text> with",
    "    a <clipPath>/<tspan>/stroke — no outlines needed.)",
    "  · Keyframe the driver in the spec for control over WHEN the morph happens:",
    '      "params": { "morph": 0 }, "keyframes": [{ "at": 0.5, "params": { "morph": 0 } },',
    '                                              { "at": 1.4, "params": { "morph": 1 }, "ease": "easeInOut" }]',
    "  · Check it with `kino still --around <t>`: the tiles must show intermediate shapes, not two states.",
    "  · Motion beats only (kind:\"motion\" / motionOverlay). A background html TEXTURE channel is",
    "    rasterised from a template built once per render, so neither this nor data-kino-vel animates",
    "    there — put the morph in a motion beat, or shape it in the shader.",
    "",
    "Procedural graphics (.js) — when a layout needs loops/computed geometry, point source at a .js",
    "file whose body is render(env) and returns an HTML string. kino calls it every frame:",
    "  // assets/motion/bars.js",
    "  const data = [40, 75, 55, 90];",
    "  return data.map((h, i) => `<div class='bar kino-anim' style='left:${8 + i * 22}%;height:${h}%;`",
    "    + `--kino-delay:${i * .08}'></div>`).join('')",
    "    + `<style>.bar{position:absolute;bottom:10%;width:8%;background:var(--kino-mint);`",
    "    + `transform-origin:bottom;transform:scaleY(var(--progress))}</style>`;",
    "  · env = { frame, t, progress, out, inout, overshoot, spring, edge, pulse, params,",
    "           palette:{mint,green,night,white,gold,font}, width, height, words? }",
    "           (out/inout/… = eased progress; edge = sin(progress·π); words = beat-relative VO).",
    "  · The returned markup can use the variables above + .kino-anim / .kino-cliptext.",
    "  · Pure (env)->string: no Date.now/Math.random/timers/fetch/import/process (the build lints it).",
    "  · Comments + string/template contents are blanked before the lint scan — \"prompt-window.js\" is OK.",
    "  · ${…} expressions inside templates are still scanned — `${window.location}` is banned.",
    "  · End-of-beat → env.progress > ~0.95 or env.edge near 0 (progress never equals 1.0).",
    "",
    "Camera zoom/pan: CSS transform on a wrapper (scale/translate driven by --kino-out / --kino-edge,",
    "a keyframed param, or typed-char fraction from env.words). Motion graphics do NOT use zoomKeyframes",
    "(that track is for app footage + frame chrome). Zooming a motionOverlay on a static PNG desyncs",
    "text from chrome — put chrome+text in one motion beat. See skills/speech-synced-ui.",
    "",
    "Make it move (agents under-animate — opacity fade alone is not enough):",
    "  ≥3 layers: entrance (stagger kino-pop / @keyframes / overshoot params)",
    "           + continuous life (--t drift, looping Lottie, caret)",
    "           + speech lock (triggers / env.words / kino-pulse) and/or CSS camera push.",
    "  Multi-step UIs: light off env.words when VO names those steps (fixed clocks → dead tails).",
    "  Stagger when ≥2 elements share the frame. Prefer too much intentional motion, then dial back.",
    "  skills/video-production § Make motion graphics move / Real VO retune / Seamless loops.",
    "",
    "Preview loop (do this — a midpoint still hides animation):",
    "  kino still <spec> --segment N          # layout / opaque Lottie bg",
    "  kino still <spec> --at 0               # ready poster (segment ≠ t=0)",
    "  kino still <spec> --around <t>         # progression sheet — tiles must look different",
    "  Prefer per-beat harness specs — full video encodes are slow.",
    "  …edit… still --around again…          # every non-trivial change",
    "  After real VO: frames <mp4> --around <t> then retune word-gated schedules",
    "",
    "Rules (the build rejects violations):",
    "  · No CSS transition, no <script>, no JS timers/RAF, no Date.now/Math.random, and don't set",
    "    animation-play-state. Use CSS variables or .kino-anim @keyframes — both are frame-driven.",
    "  · Inline images as data: URIs (external/relative url() won't resolve in the render).",
    "  · Anchor keyframes/triggers to spoken words with atWord (\"atWord\": \"match\" or a word index)",
    "    instead of at seconds — resolved against the build's real VO timings, no mock→real retune.",
    "    Base params are an implicit t=0 keyframe: a lone keyframe tweens from the base value.",
    "  · For at-second moments, sync with `kino inspect`; preview a word with `kino still --segment N --word <w>`.",
    "",
    "Lottie graphics (.json, Tier 3) — embed a designer-made Bodymovin/LottieFiles animation by",
    'pointing source at a .json file: { "kind": "motion", "source": "motion/confetti.json", "text": "..." }.',
    "It plays once stretched across the beat; add \"loop\": true (sibling of source) to loop at native speed.",
    "Word-fire: give the Lottie triggers at VO word times (from kino inspect) — { ..., \"triggers\":",
    "[{ \"at\": 0.4, \"action\": \"play\" }, ...] } — and each trigger pops a fresh one-shot in sync with the",
    "words (use a short, transparent burst asset). Triggers override stretch/loop.",
    "Rules: assets must embed images (base64 data: URIs) and outline/embed fonts (no system fonts);",
    "After Effects expressions are rejected. For a motionOverlay, use a TRANSPARENT-background export —",
    "an opaque background hides the avatar/app underneath. Keep focal content clear of the lower-third caption.",
  ].join("\n");
}

export async function motion(): Promise<void> {
  process.stdout.write(motionHelpText());
}
