// Discovery: print the CSS-variable contract + rules an agent codes a motion-graphic HTML file
// against. Mirrors `kino backgrounds`/`kino elements`. The graphic is referenced from the spec
// (kind:"motion" or motionOverlay) and driven entirely by these kino-set variables.
import { listMotionIds } from "../media/motionLib.js";

export function motionHelpText(): string {
  const lib = listMotionIds();
  const libLine = lib.length
    ? `Bundled library ids (bare source, no path): ${lib.join(", ")}`
    : "Bundled library: (empty assets-lib/motion/)";
  return [
    "Motion graphics — author a self-contained HTML/CSS/.js file in assets/motion/, OR use a bare",
    "id from assets-lib/motion/ (e.g. \"source\": \"prompt-type\"). Reference from the spec:",
    '  { "kind": "motion", "source": "motion/x.html" | "prompt-type", "text": "..." }',
    "  or \"motionOverlay\". JSON owns timing; CSS/JS reads kino-set variables.",
    "",
    `  ${libLine}`,
    "",
    "  --frame      integer frame within the beat",
    "  --t          seconds within the beat — real render clock; use for scrubbers / elapsed timers",
    "  --progress   0 → 1 across the beat (entrances, camera — not playback clocks)",
    "  --kino-in / --kino-out / --kino-inout / --kino-overshoot / --kino-spring / --kino-edge",
    "               eased progress curves (prefer for entrances/camera/seam-safe life)",
    "  Keyframe ease (per keyframe `ease` on params): linear · easeIn · easeOut · easeInOut ·",
    "    easeInQuad/easeOutQuad/easeInOutQuad · easeInCubic/easeOutCubic/easeInOutCubic ·",
    "    easeInQuart/easeOutQuart/easeInOutQuart · easeInExpo/easeOutExpo/easeInOutExpo ·",
    "    overshoot · spring",
    "  --pulse      0 → 1 envelope fired by spec triggers ({ at, action:'pulse' })",
    "  --cam-vel    |cam[t] − cam[t−1]| × fps (0 when no cam param or frame 0)",
    "  --cam-blur   camBlur × camVel × (1 − cam), px-ready, clamped 0..24 (default camBlur=12)",
    "  --<param>    every key in the spec's params, tweened by keyframes (e.g. --pct, --cam)",
    "  --kino-green --kino-night --kino-white --kino-mint --kino-gold   brand palette",
    "  --kino-font  brand font family",
    "  --kino-caption-bottom   px from the frame bottom where kino's caption sits (0 = no caption",
    "               this beat). Keep your own text clear of it — sit above the band with",
    "               bottom:calc(var(--kino-caption-bottom) + 24px), or below it toward the frame",
    "               bottom with bottom:max(24px, calc(var(--kino-caption-bottom) - 160px)).",
    "  --kino-words-shown / --kino-word-count   VO-locked typed UI. words-shown is CONTINUOUS —",
    "               each word contributes its elapsed fraction across its spoken span, so gated",
    "               reveals (clamp(0, calc(var(--kino-words-shown) - i), 1)) ease, not step.",
    "               Tier-2 JS also gets env.words = beat-relative { word, start, end }[] — same",
    "               TTS timings as the caption engine.",
    "               Recipes: skills/speech-synced-ui (burst typewriter, camera-follows-typing).",
    "",
    "Example (a bar that grows to --pct and a title that rises in):",
    "  <style>",
    "    .bar   { position:absolute; left:8%; bottom:30%; height:48px;",
    "             width:calc(var(--pct) * 1%); background:var(--kino-mint); border-radius:8px; }",
    "    .title { position:absolute; left:8%; bottom:38%; font-family:var(--kino-font);",
    "             color:var(--kino-white); font-weight:900; font-size:64px;",
    "             opacity:var(--progress);",
    "             transform:translateY(calc((1 - var(--progress)) * 40px)); }",
    "  </style>",
    "  <div class='title'>86% match</div><div class='bar'></div>",
    "",
    "Drive it from the spec:",
    '  "params": { "pct": 0 }, "keyframes": [{ "at": 0, "params": { "pct": 0 } }, { "at": 0.6, "params": { "pct": 86 }, "ease": "overshoot" }]',
    "  · `at` is beat-relative SECONDS (0 = beat start), like zoomKeyframes / triggers — NOT a 0-1 fraction.",
    "  · ONE keyframe holds that value static for the whole beat; give a START + END pair to animate (a lone",
    "    { at:0.2, pct:86 } paints 86 from frame 0 — the bar never grows).",
    "",
    "Stagger (reveal items one after another — don't let everything land at once):",
    "  · Easiest — auto-stagger a whole list with sibling-index() (one rule, no extra params):",
    "      .item { --d: calc((sibling-index() - 1) * .08);",
    "              opacity: clamp(0, calc((var(--progress) - .2 - var(--d)) * 8), 1); }",
    "  · Or give each element its own slice of --progress:",
    "      .a { opacity: clamp(0, calc(var(--progress) * 10), 1); }",
    "      .b { opacity: clamp(0, calc((var(--progress) - .12) * 10), 1); }",
    "  · Or expose a param per element (--w1/--w2 …) and offset the keyframe `at` times to get",
    "    spring / overshoot / easeInOut easing per element.",
    "",
    "Keep it calm: easeInOut (or a smoothstep ramp) reads smoother than spring; let entrances last",
    "~1s and add slow continuous life off --t (e.g. transform:rotate(calc(var(--t) * 20deg))).",
    "",
    "Use real @keyframes (kino scrubs them across the beat — add class=\"kino-anim\"):",
    "  <style>@keyframes pop{0%{transform:scale(.6);opacity:0} 60%{transform:scale(1.06)}",
    "                        100%{transform:scale(1);opacity:1}}",
    "         .badge{animation-name:pop}</style>",
    "  <div class='badge kino-anim'>NEW</div>",
    "  · The animation plays 0→100% across the whole beat — put sub-timing in the % stops.",
    "  · Stagger items with --kino-delay (pairs with sibling-index):",
    "      .kw{ --kino-delay: calc((sibling-index() - 1) * .1); }",
    "  · Don't set animation-play-state — kino manages pausing. (CSS transition is still not allowed.)",
    "",
    "Gradient-filled text — background-clip:text + tight (negative) letter-spacing clips the last",
    'glyph\'s right edge (the gradient only paints the content box). Add class="kino-cliptext":',
    "  .big{ background-image:linear-gradient(var(--kino-mint), var(--kino-white));",
    "        -webkit-background-clip:text; background-clip:text; color:transparent; letter-spacing:-.04em }",
    "  <div class='big kino-cliptext'>98%</div>",
    "",
    "Built-in helper classes (opt-in; no @keyframes to write; all frame-driven + determinism-safe):",
    "  · Reveals that complete in the first ~third of the beat then hold — class=\"kino-rise\" (fade +",
    "    slide up), \"kino-blur-rise\", \"kino-pop\" (overshoot), \"kino-wipe\" (clip-reveal). Stagger a",
    "    list with --kino-delay: e.g. .item{ --kino-delay: calc((sibling-index() - 1) * .08) }.",
    "  · class=\"kino-pulse\" — opacity+scale pop on each spec trigger { at, action:'pulse' } (place the",
    "    triggers at VO word times from `kino inspect` to punch on the words). Accent-only: sets",
    "    opacity:var(--pulse,0) so the element is hidden between triggers — never on always-visible",
    "    primary chrome (play buttons, nav bars). Use var(--pulse) in your own CSS for subtle reacts.",
    "  · class=\"kino-camera\" — velocity-blur on camera moves. Keyframe cam:0→1 in spec params;",
    "    blur peaks mid-move and clears on settle. Optional camBlur param (default 12). Tier-2:",
    "    env.camVel / env.camBlur.",
    "  · class=\"kino-fade-edges\" — feathers the top/bottom edges (scrolling lists / overflowing text).",
    "  · Easing tokens for your own @keyframes: animation-timing-function:var(--kino-ease-out) (also",
    "    --kino-ease-in-out, --kino-ease-overshoot, --kino-ease-spring).",
    "  · Texture & finish: class=\"kino-grain\" (film grain), \"kino-vignette\" (edge darken), \"kino-mesh\"",
    "    (soft palette-gradient background), \"kino-shadow\" (soft drop-shadow). Or apply the injected SVG",
    "    filters directly: filter:url(#kino-grain) or filter:url(#kino-displace) (organic edge wobble).",
    "",
    "Procedural graphics (.js) — when a layout needs loops/computed geometry, point source at a .js",
    "file whose body is render(env) and returns an HTML string. kino calls it every frame:",
    "  // assets/motion/bars.js",
    "  const data = [40, 75, 55, 90];",
    "  return data.map((h, i) => `<div class='bar kino-anim' style='left:${8 + i * 22}%;height:${h}%;`",
    "    + `--kino-delay:${i * .08}'></div>`).join('')",
    "    + `<style>.bar{position:absolute;bottom:10%;width:8%;background:var(--kino-mint);`",
    "    + `transform-origin:bottom;transform:scaleY(var(--progress))}</style>`;",
    "  · env = { frame, t, progress, out, inout, overshoot, spring, edge, pulse, params,",
    "           palette:{mint,green,night,white,gold,font}, width, height, words? }",
    "           (out/inout/… = eased progress; edge = sin(progress·π); words = beat-relative VO).",
    "  · The returned markup can use the variables above + .kino-anim / .kino-cliptext.",
    "  · Pure (env)->string: no Date.now/Math.random/timers/fetch/import/process (the build lints it).",
    "  · Comments + string/template contents are blanked before the lint scan — \"prompt-window.js\" is OK.",
    "  · ${…} expressions inside templates are still scanned — `${window.location}` is banned.",
    "  · End-of-beat → env.progress > ~0.95 or env.edge near 0 (progress never equals 1.0).",
    "",
    "Camera zoom/pan: CSS transform on a wrapper (scale/translate driven by --kino-out / --kino-edge,",
    "a keyframed param, or typed-char fraction from env.words). Motion graphics do NOT use zoomKeyframes",
    "(that track is for app footage + frame chrome). Zooming a motionOverlay on a static PNG desyncs",
    "text from chrome — put chrome+text in one motion beat. See skills/speech-synced-ui.",
    "",
    "Make it move (agents under-animate — opacity fade alone is not enough):",
    "  ≥3 layers: entrance (stagger kino-pop / @keyframes / overshoot params)",
    "           + continuous life (--t drift, looping Lottie, caret)",
    "           + speech lock (triggers / env.words / kino-pulse) and/or CSS camera push.",
    "  Multi-step UIs: light off env.words when VO names those steps (fixed clocks → dead tails).",
    "  Stagger when ≥2 elements share the frame. Prefer too much intentional motion, then dial back.",
    "  skills/video-production § Make motion graphics move / Real VO retune / Seamless loops.",
    "",
    "Preview loop (do this — a midpoint still hides animation):",
    "  kino still <spec> --segment N          # layout / opaque Lottie bg",
    "  kino still <spec> --at 0               # ready poster (segment ≠ t=0)",
    "  kino still <spec> --around <t>         # progression sheet — tiles must look different",
    "  Prefer per-beat harness specs — full video encodes are slow.",
    "  …edit… still --around again…          # every non-trivial change",
    "  After real VO: frames <mp4> --around <t> then retune word-gated schedules",
    "",
    "Rules (the build rejects violations):",
    "  · No CSS transition, no <script>, no JS timers/RAF, no Date.now/Math.random, and don't set",
    "    animation-play-state. Use CSS variables or .kino-anim @keyframes — both are frame-driven.",
    "  · Inline images as data: URIs (external/relative url() won't resolve in the render).",
    "  · Anchor keyframes/triggers to spoken words with atWord (\"atWord\": \"match\" or a word index)",
    "    instead of at seconds — resolved against the build's real VO timings, no mock→real retune.",
    "    Base params are an implicit t=0 keyframe: a lone keyframe tweens from the base value.",
    "  · For at-second moments, sync with `kino inspect`; preview a word with `kino still --segment N --word <w>`.",
    "",
    "Lottie graphics (.json, Tier 3) — embed a designer-made Bodymovin/LottieFiles animation by",
    'pointing source at a .json file: { "kind": "motion", "source": "motion/confetti.json", "text": "..." }.',
    "It plays once stretched across the beat; add \"loop\": true (sibling of source) to loop at native speed.",
    "Word-fire: give the Lottie triggers at VO word times (from kino inspect) — { ..., \"triggers\":",
    "[{ \"at\": 0.4, \"action\": \"play\" }, ...] } — and each trigger pops a fresh one-shot in sync with the",
    "words (use a short, transparent burst asset). Triggers override stretch/loop.",
    "Rules: assets must embed images (base64 data: URIs) and outline/embed fonts (no system fonts);",
    "After Effects expressions are rejected. For a motionOverlay, use a TRANSPARENT-background export —",
    "an opaque background hides the avatar/app underneath. Keep focal content clear of the lower-third caption.",
  ].join("\n");
}

export async function motion(): Promise<void> {
  process.stdout.write(motionHelpText());
}
