// Discovery: print the CSS-variable contract + rules an agent codes a motion-graphic HTML file
// against. Mirrors `kino backgrounds`/`kino elements`. The graphic is referenced from the spec
// (kind:"motion" or motionOverlay) and driven entirely by these kino-set variables.
export function motionHelpText(): string {
  return [
    "Motion graphics — author a self-contained HTML/CSS file in assets/motion/, reference it from",
    'the spec ({ "kind": "motion", "source": "motion/x.html", "text": "..." } or "motionOverlay").',
    "JSON owns timing; your CSS reads kino-set variables. Motion = a function of these vars:",
    "",
    "  --frame      integer frame within the beat",
    "  --t          seconds within the beat",
    "  --progress   0 → 1 across the beat (use for entrances/reveals)",
    "  --pulse      0 → 1 envelope fired by spec triggers ({ at, action:'pulse' })",
    "  --<param>    every key in the spec's params, tweened by keyframes (e.g. --pct)",
    "  --kino-green --kino-night --kino-white --kino-mint   brand palette",
    "  --kino-font  brand font family",
    "",
    "Example (a bar that grows to --pct and a title that rises in):",
    "  <style>",
    "    .bar   { position:absolute; left:8%; bottom:30%; height:48px;",
    "             width:calc(var(--pct) * 1%); background:var(--kino-mint); border-radius:8px; }",
    "    .title { position:absolute; left:8%; bottom:38%; font-family:var(--kino-font);",
    "             color:var(--kino-white); font-weight:900; font-size:64px;",
    "             opacity:var(--progress);",
    "             transform:translateY(calc((1 - var(--progress)) * 40px)); }",
    "  </style>",
    "  <div class='title'>86% match</div><div class='bar'></div>",
    "",
    "Drive it from the spec:",
    '  "params": { "pct": 0 }, "keyframes": [{ "at": 0.2, "params": { "pct": 86 }, "ease": "overshoot" }]',
    "",
    "Stagger (reveal items one after another — don't let everything land at once):",
    "  · Easiest — auto-stagger a whole list with sibling-index() (one rule, no extra params):",
    "      .item { --d: calc((sibling-index() - 1) * .08);",
    "              opacity: clamp(0, calc((var(--progress) - .2 - var(--d)) * 8), 1); }",
    "  · Or give each element its own slice of --progress:",
    "      .a { opacity: clamp(0, calc(var(--progress) * 10), 1); }",
    "      .b { opacity: clamp(0, calc((var(--progress) - .12) * 10), 1); }",
    "  · Or expose a param per element (--w1/--w2 …) and offset the keyframe `at` times to get",
    "    spring / overshoot / easeInOut easing per element.",
    "",
    "Keep it calm: easeInOut (or a smoothstep ramp) reads smoother than spring; let entrances last",
    "~1s and add slow continuous life off --t (e.g. transform:rotate(calc(var(--t) * 20deg))).",
    "",
    "Use real @keyframes (kino scrubs them across the beat — add class=\"kino-anim\"):",
    "  <style>@keyframes pop{0%{transform:scale(.6);opacity:0} 60%{transform:scale(1.06)}",
    "                        100%{transform:scale(1);opacity:1}}",
    "         .badge{animation-name:pop}</style>",
    "  <div class='badge kino-anim'>NEW</div>",
    "  · The animation plays 0→100% across the whole beat — put sub-timing in the % stops.",
    "  · Stagger items with --kino-delay (pairs with sibling-index):",
    "      .kw{ --kino-delay: calc((sibling-index() - 1) * .1); }",
    "  · Don't set animation-play-state — kino manages pausing. (CSS transition is still not allowed.)",
    "",
    "Gradient-filled text — background-clip:text + tight (negative) letter-spacing clips the last",
    'glyph\'s right edge (the gradient only paints the content box). Add class="kino-cliptext":',
    "  .big{ background-image:linear-gradient(var(--kino-mint), var(--kino-white));",
    "        -webkit-background-clip:text; background-clip:text; color:transparent; letter-spacing:-.04em }",
    "  <div class='big kino-cliptext'>98%</div>",
    "",
    "Procedural graphics (.js) — when a layout needs loops/computed geometry, point source at a .js",
    "file whose body is render(env) and returns an HTML string. kino calls it every frame:",
    "  // assets/motion/bars.js",
    "  const data = [40, 75, 55, 90];",
    "  return data.map((h, i) => `<div class='bar kino-anim' style='left:${8 + i * 22}%;height:${h}%;`",
    "    + `--kino-delay:${i * .08}'></div>`).join('')",
    "    + `<style>.bar{position:absolute;bottom:10%;width:8%;background:var(--kino-mint);`",
    "    + `transform-origin:bottom;transform:scaleY(var(--progress))}</style>`;",
    "  · env = { frame, t, progress, pulse, params, palette:{mint,green,night,white,gold,font}, width, height }.",
    "  · The returned markup can use the variables above + .kino-anim / .kino-cliptext.",
    "  · Pure (env)->string: no Date.now/Math.random/timers/fetch/import/process (the build lints it).",
    "",
    "Rules (the build rejects violations):",
    "  · No CSS transition, no <script>, no JS timers/RAF, no Date.now/Math.random, and don't set",
    "    animation-play-state. Use CSS variables or .kino-anim @keyframes — both are frame-driven.",
    "  · Inline images as data: URIs (external/relative url() won't resolve in the render).",
    "  · Sync timings to the VO with `kino inspect` (per-word start/end).",
    "",
  ].join("\n");
}

export async function motion(): Promise<void> {
  process.stdout.write(motionHelpText());
}
