// kino update — self-update matched to how kino was installed:
//   git clone + npm link → git pull --ff-only, npm install, npm run build
//   npm i -g            → npm install -g @sdkv2/kino@latest
//   npx                 → nothing to do (npx resolves fresh each first run)
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { execa } from "execa";
import { log } from "../log.js";

export type InstallKind = "git" | "global" | "npx";

/** How this kino was installed, from its package root. `exists` injectable for tests. */
export function detectInstallKind(packageRoot: string, exists: (p: string) => boolean = existsSync): InstallKind {
  if (exists(join(packageRoot, ".git"))) return "git";
  if (packageRoot.split(sep).includes("_npx")) return "npx";
  return "global";
}

/** Classify `git status --porcelain` output: older npm versions rewrite package-lock.json on a
 *  plain install, which would abort every future pull — that alone is safe to reset (npm install
 *  regenerates it right after). Anything else is the user's work; never discard it. */
export function classifyWorkingTree(porcelain: string): "clean" | "reset-lock" | "dirty" {
  const lines = porcelain.split("\n").filter((l) => l.trim());
  if (!lines.length) return "clean";
  return lines.every((l) => l.trim().endsWith("package-lock.json")) ? "reset-lock" : "dirty";
}

const version = (root: string): string => {
  try {
    return JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version ?? "?";
  } catch {
    return "?";
  }
};

export async function update(): Promise<void> {
  // dist/commands/update.js → package root two levels up.
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
  const kind = detectInstallKind(root);
  const before = version(root);

  if (kind === "npx") {
    log.info(`running via npx (${before}) — npx fetches the latest on each fresh run; nothing to update`);
    return;
  }
  if (kind === "global") {
    log.step(`npm install -g @sdkv2/kino@latest (current ${before})`);
    await execa("npm", ["install", "-g", "@sdkv2/kino@latest"], { stdio: "inherit" });
    log.ok("updated — run `kino --version` to confirm");
    return;
  }

  log.step(`git pull (repo install at ${root}, current ${before})`);
  const status = await execa("git", ["status", "--porcelain"], { cwd: root });
  const tree = classifyWorkingTree(status.stdout);
  if (tree === "dirty") {
    throw new Error(`local changes in ${root} — commit or stash them, then re-run kino update`);
  }
  if (tree === "reset-lock") {
    // npm-version churn on the lockfile; regenerated by the npm install below.
    await execa("git", ["checkout", "--", "package-lock.json"], { cwd: root });
  }
  const pull = await execa("git", ["pull", "--ff-only"], { cwd: root, reject: false });
  if (pull.exitCode !== 0) {
    throw new Error(`git pull failed — ${pull.stderr.split("\n")[0] || "resolve manually in " + root}`);
  }
  if (/Already up to date/i.test(pull.stdout)) {
    log.ok(`already up to date (${before})`);
    return;
  }
  log.step("npm install");
  await execa("npm", ["install", "--no-audit", "--no-fund"], { cwd: root, stdio: "inherit" });
  log.step("npm run build");
  await execa("npm", ["run", "build"], { cwd: root, stdio: "inherit" });
  log.ok(`updated ${before} → ${version(root)}`);
}
