// The render page ships two ways:
//   • dev (repo checkout, running from src via tsx/vitest): bundle page/index.tsx on the fly with
//     esbuild (devDependency — present in the repo, never needed by installed users);
//   • published (running from dist): read the prebuilt page.bundle.js emitted by `npm run build`
//     (scripts/build-page.mjs), shipped inside dist/.
// The prebuilt file is regenerated by every `npm run build`, which the repo already treats as the
// gate for dist freshness.
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

export async function getPageBundle(): Promise<string> {
  const devEntry = join(here, "page", "index.tsx");
  if (existsSync(devEntry)) {
    const esbuild = await import("esbuild");
    const result = await esbuild.build({
      entryPoints: [devEntry],
      bundle: true,
      write: false,
      format: "iife",
      platform: "browser",
      target: "chrome120",
      jsx: "automatic",
      define: { "process.env.NODE_ENV": '"production"' },
      logLevel: "silent",
    });
    return result.outputFiles[0].text;
  }
  const prebuilt = join(here, "page.bundle.js");
  if (!existsSync(prebuilt)) {
    throw new Error(`native render page bundle missing at ${prebuilt} — run \`npm run build\``);
  }
  return readFileSync(prebuilt, "utf8");
}
